version: '3'
services:
  # generates weather reports
  app-service:
    image: service-app
    container_name: app-service
    depends_on:
      - batch-service
    ports:
      - 5001:18080
    restart: on-failure

  # Retrieves the temperature
  batch-service:
    image: batch-app
    container_name: batch-service
    ports:
      - 5002:18081
    restart: on-failure

