version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx
    container_name: reverse_proxy_demo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      #- ./etc/nginx/conf.d/config1.conf:/etc/nginx/conf.d/config1.conf
    ports:
      - 80:80
